"""Чистые части DNAT-менеджера: проверка набора, генерация restore-скрипта,
разбор дампа с счётчиками, хэш и файл состояния.

Запуск из node/:  python -m unittest discover -s tests -p "test_*.py"
"""

import asyncio
import json
import os
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.models.dnat import DnatRule  # noqa: E402
from app.services.dnat_manager import (  # noqa: E402
    CHAIN_FORWARD,
    CHAIN_MANGLE,
    CHAIN_POSTROUTING,
    CHAIN_PREROUTING,
    DnatManager,
    build_restore_script,
    compute_rules_hash,
    parse_dump,
    summarize,
    validate_rules,
)


def rule(**overrides) -> DnatRule:
    base = {"name": "vless", "protocol": "tcp", "listen_port": 443, "target_ip": "10.0.0.2", "target_port": 8443}
    base.update(overrides)
    return DnatRule(**base)


NAT_DUMP = """\
# Generated by iptables-save v1.8.10
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:DOCKER - [0:0]
:MON_DNAT - [0:0]
:MON_DNAT_POST - [0:0]
[10:600] -A PREROUTING -j MON_DNAT
[3:200] -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
[10:600] -A POSTROUTING -j MON_DNAT_POST
[7:420] -A MON_DNAT -p tcp -m tcp --dport 443 -m comment --comment "mon-dnat:vless@10.0.0.2" -j DNAT --to-destination 10.0.0.2:8443
[2:120] -A MON_DNAT -p udp -m udp --dport 20000:30000 -m comment --comment "mon-dnat:hop@10.0.0.3" -j DNAT --to-destination 10.0.0.3:443
[7:420] -A MON_DNAT_POST -d 10.0.0.2/32 -p tcp -m tcp --dport 8443 -m conntrack --ctstate DNAT -m comment --comment "mon-dnat:vless@10.0.0.2" -j MASQUERADE
COMMIT
"""

FILTER_DUMP = """\
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
:MON_DNAT_FWD - [0:0]
[500:40000] -A FORWARD -j MON_DNAT_FWD
[300:20000] -A MON_DNAT_FWD -d 10.0.0.2/32 -p tcp -m tcp --dport 8443 -m conntrack --ctstate DNAT -m comment --comment "mon-dnat:vless:in@10.0.0.2" -j ACCEPT
[200:900000] -A MON_DNAT_FWD -s 10.0.0.2/32 -p tcp -m tcp --sport 8443 -m conntrack --ctstate DNAT -m comment --comment "mon-dnat:vless:out@10.0.0.2" -j ACCEPT
[0:0] -A MON_DNAT_FWD -m conntrack --ctstate RELATED -m comment --comment "mon-dnat:related" -j ACCEPT
COMMIT
"""

MANGLE_DUMP = """\
*mangle
:PREROUTING ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:MON_DNAT_MANGLE - [0:0]
[500:40000] -A FORWARD -j MON_DNAT_MANGLE
COMMIT
"""


class ValidateRulesTest(unittest.TestCase):
    def test_accepts_disjoint_rules(self):
        self.assertIsNone(validate_rules([rule(), rule(name="udp", protocol="udp", listen_port=443)]))

    def test_rejects_duplicate_names(self):
        self.assertIn("Duplicate", validate_rules([rule(), rule(listen_port=444)]))

    def test_rejects_overlapping_ports_same_protocol(self):
        error = validate_rules([
            rule(name="a", listen_port=1000, listen_port_end=2000),
            rule(name="b", listen_port=1500),
        ])
        self.assertIn("overlap", error)

    def test_both_protocol_overlaps_with_tcp(self):
        error = validate_rules([rule(name="a", protocol="both"), rule(name="b", listen_port=443)])
        self.assertIn("overlap", error)

    def test_disabled_rule_does_not_conflict(self):
        self.assertIsNone(validate_rules([rule(name="a"), rule(name="b", enabled=False)]))

    def test_rejects_node_api_port(self):
        self.assertIn("9100", validate_rules([rule(listen_port=9000, listen_port_end=9200)]))
        # udp на 9100 не мешает mTLS-nginx
        self.assertIsNone(validate_rules([rule(protocol="udp", listen_port=9100)]))


class RuleModelTest(unittest.TestCase):
    def test_range_end_equal_to_start_collapses(self):
        self.assertIsNone(rule(listen_port_end=443).listen_port_end)

    def test_range_end_below_start_rejected(self):
        with self.assertRaises(ValueError):
            rule(listen_port_end=100)

    def test_target_must_be_ipv4(self):
        for bad in ("example.com", "::1", "0.0.0.0", "224.0.0.1", "", "10.0.0.2, host"):
            with self.subTest(bad=bad), self.assertRaises(ValueError):
                rule(target_ip=bad)

    def test_target_list_is_normalized(self):
        self.assertEqual(rule(target_ip=" 10.0.0.2 ,10.0.0.3, 10.0.0.2").target_ip, "10.0.0.2,10.0.0.3")
        self.assertEqual(rule(target_ip="10.0.0.2,10.0.0.3").targets(), ["10.0.0.2", "10.0.0.3"])

    def test_per_server_with_several_targets_is_rejected_by_validate(self):
        self.assertIn("distribution", validate_rules([rule(target_ip="10.0.0.2,10.0.0.3")]))
        self.assertIsNone(validate_rules([rule(target_ip="10.0.0.2,10.0.0.3", distribution="random")]))


class RestoreScriptTest(unittest.TestCase):
    def test_single_port_rule(self):
        script = build_restore_script([rule()])
        self.assertIn("*nat", script)
        self.assertIn(f":{CHAIN_PREROUTING} - [0:0]", script)
        self.assertIn(f"-F {CHAIN_PREROUTING}", script)
        self.assertIn(
            f'-A {CHAIN_PREROUTING} -p tcp --dport 443 -m comment --comment "mon-dnat:vless@10.0.0.2" -j DNAT --to-destination 10.0.0.2:8443',
            script,
        )
        self.assertIn(
            f'-A {CHAIN_POSTROUTING} -p tcp -d 10.0.0.2 --dport 8443 -m conntrack --ctstate DNAT -m comment --comment "mon-dnat:vless@10.0.0.2" -j MASQUERADE',
            script,
        )
        self.assertIn(f'-A {CHAIN_FORWARD} -p tcp -d 10.0.0.2 --dport 8443 -m conntrack --ctstate DNAT -m comment --comment "mon-dnat:vless:in@10.0.0.2" -j ACCEPT', script)
        self.assertIn(f'-A {CHAIN_FORWARD} -p tcp -s 10.0.0.2 --sport 8443 -m conntrack --ctstate DNAT -m comment --comment "mon-dnat:vless:out@10.0.0.2" -j ACCEPT', script)
        self.assertEqual(script.count("COMMIT"), 3)
        self.assertNotIn("statistic", script)
        self.assertNotIn("HMARK", script)
        # без mask_ttl цепочка mangle объявляется пустой
        self.assertIn(f":{CHAIN_MANGLE} - [0:0]", script)
        self.assertNotIn("-j TTL", script)
        self.assertNotIn("TCPMSS", script)

    def test_mask_ttl_adds_mangle_rules_both_directions(self):
        script = build_restore_script([rule(mask_ttl=True, protocol="both")])
        self.assertIn(f'-A {CHAIN_MANGLE} -p tcp -d 10.0.0.2 --dport 8443 -m conntrack --ctstate DNAT -m comment --comment "mon-dnat:vless:ttl-in@10.0.0.2" -j TTL --ttl-set 64', script)
        self.assertIn(f'-A {CHAIN_MANGLE} -p tcp -s 10.0.0.2 --sport 8443 -m conntrack --ctstate DNAT -m comment --comment "mon-dnat:vless:ttl-out@10.0.0.2" -j TTL --ttl-set 64', script)
        self.assertIn(f'-A {CHAIN_MANGLE} -p udp -d 10.0.0.2 --dport 8443 -m conntrack --ctstate DNAT -m comment --comment "mon-dnat:vless:ttl-in@10.0.0.2" -j TTL --ttl-set 64', script)
        # MSS clamp — только tcp и только SYN
        self.assertIn(f'-A {CHAIN_MANGLE} -p tcp -d 10.0.0.2 --dport 8443 --tcp-flags SYN,RST SYN -m conntrack --ctstate DNAT -m comment --comment "mon-dnat:vless:mss@10.0.0.2" -j TCPMSS --clamp-mss-to-pmtu', script)
        self.assertNotIn("-p udp -d 10.0.0.2 --dport 8443 --tcp-flags", script)

    def test_random_distribution_chains_probabilities(self):
        script = build_restore_script([rule(target_ip="10.0.0.2,10.0.0.3,10.0.0.4", distribution="random")])
        self.assertIn('--dport 443 -m statistic --mode random --probability 0.333333 -m comment --comment "mon-dnat:vless@10.0.0.2" -j DNAT --to-destination 10.0.0.2:8443', script)
        self.assertIn('--dport 443 -m statistic --mode random --probability 0.500000 -m comment --comment "mon-dnat:vless@10.0.0.3" -j DNAT --to-destination 10.0.0.3:8443', script)
        # последняя цель — без условия
        self.assertIn('--dport 443 -m comment --comment "mon-dnat:vless@10.0.0.4" -j DNAT --to-destination 10.0.0.4:8443', script)
        # MASQUERADE и FORWARD — на каждую цель
        for ip in ("10.0.0.2", "10.0.0.3", "10.0.0.4"):
            self.assertIn(f'-d {ip} --dport 8443 -m conntrack --ctstate DNAT -m comment --comment "mon-dnat:vless@{ip}" -j MASQUERADE', script)
            self.assertIn(f'"mon-dnat:vless:in@{ip}"', script)
            self.assertIn(f'"mon-dnat:vless:out@{ip}"', script)

    def test_round_robin_uses_nth(self):
        script = build_restore_script([rule(target_ip="10.0.0.2,10.0.0.3,10.0.0.4", distribution="round_robin")])
        self.assertIn('-m statistic --mode nth --every 3 --packet 0 -m comment --comment "mon-dnat:vless@10.0.0.2"', script)
        self.assertIn('-m statistic --mode nth --every 2 --packet 0 -m comment --comment "mon-dnat:vless@10.0.0.3"', script)
        self.assertIn('--dport 443 -m comment --comment "mon-dnat:vless@10.0.0.4"', script)

    def test_client_hash_marks_then_matches(self):
        script = build_restore_script([rule(target_ip="10.0.0.2,10.0.0.3", distribution="client_hash")])
        lines = script.splitlines()
        hmark = next(i for i, l in enumerate(lines) if "-j HMARK" in l)
        self.assertIn('--hmark-tuple src --hmark-mod 2 --hmark-offset 0x4d440000', lines[hmark])
        self.assertIn('"mon-dnat:vless#hash"', lines[hmark])
        first = next(i for i, l in enumerate(lines) if "-m mark --mark 0x4d440000 " in l)
        second = next(i for i, l in enumerate(lines) if "-m mark --mark 0x4d440001 " in l)
        self.assertLess(hmark, first)
        self.assertLess(first, second)
        self.assertNotIn("statistic", script)

    def test_single_target_ignores_distribution(self):
        script = build_restore_script([rule(distribution="client_hash")])
        self.assertNotIn("HMARK", script)
        self.assertNotIn("-m mark", script)

    def test_range_keeps_ports_when_target_port_zero(self):
        script = build_restore_script([rule(name="hop", protocol="udp", listen_port=20000, listen_port_end=30000, target_port=0)])
        self.assertIn("-p udp --dport 20000:30000", script)
        self.assertIn("-j DNAT --to-destination 10.0.0.2\n", script)
        self.assertIn("-d 10.0.0.2 --dport 20000:30000 -m conntrack --ctstate DNAT", script)
        self.assertIn("-s 10.0.0.2 --sport 20000:30000", script)

    def test_both_protocols_emit_tcp_and_udp(self):
        script = build_restore_script([rule(protocol="both")])
        self.assertIn("-p tcp --dport 443", script)
        self.assertIn("-p udp --dport 443", script)

    def test_masquerade_off_and_disabled_rule(self):
        script = build_restore_script([rule(masquerade=False), rule(name="off", listen_port=444, enabled=False)])
        self.assertNotIn("MASQUERADE", script)
        self.assertNotIn("mon-dnat:off", script)
        # Цепочки всё равно объявляются и чистятся
        self.assertIn(f"-F {CHAIN_POSTROUTING}", script)


class ParseDumpTest(unittest.TestCase):
    def test_counters_and_jumps(self):
        marked, jumps = parse_dump(NAT_DUMP)
        self.assertIn(("PREROUTING", CHAIN_PREROUTING), jumps)
        self.assertIn(("POSTROUTING", CHAIN_POSTROUTING), jumps)
        self.assertNotIn(("PREROUTING", "DOCKER"), jumps)
        self.assertIn((CHAIN_PREROUTING, "vless@10.0.0.2", 7, 420), marked)
        self.assertIn((CHAIN_PREROUTING, "hop@10.0.0.3", 2, 120), marked)

    def test_summarize_counts_and_missing(self):
        rules = [rule(), rule(name="hop", protocol="udp", listen_port=20000, listen_port_end=30000, target_ip="10.0.0.3", target_port=443)]
        counters, missing = summarize(rules, NAT_DUMP, FILTER_DUMP, MANGLE_DUMP)
        by_name = {c["name"]: c for c in counters}
        self.assertTrue(by_name["vless"]["present"])
        self.assertEqual(by_name["vless"]["conns"], 7)
        self.assertEqual(by_name["vless"]["bytes_in"], 20000)
        self.assertEqual(by_name["vless"]["bytes_out"], 900000)
        self.assertEqual(by_name["vless"]["targets"][0]["ip"], "10.0.0.2")
        self.assertEqual(by_name["vless"]["targets"][0]["conns"], 7)
        # у hop нет FORWARD-правил и MASQUERADE — правило считается потерянным
        self.assertFalse(by_name["hop"]["present"])
        self.assertFalse(by_name["hop"]["targets"][0]["present"])
        self.assertEqual(missing, ["hop"])

    def test_multi_target_sums_and_requires_hash_rule(self):
        multi = rule(target_ip="10.0.0.2,10.0.0.5", distribution="client_hash")
        nat = NAT_DUMP + '[3:180] -A MON_DNAT -p tcp -m tcp --dport 443 -m mark --mark 0x4d440001 -m comment --comment "mon-dnat:vless@10.0.0.5" -j DNAT --to-destination 10.0.0.5:8443\n'
        nat += '[3:180] -A MON_DNAT_POST -d 10.0.0.5/32 -p tcp -m tcp --dport 8443 -m conntrack --ctstate DNAT -m comment --comment "mon-dnat:vless@10.0.0.5" -j MASQUERADE\n'
        fwd = FILTER_DUMP + '[10:1000] -A MON_DNAT_FWD -d 10.0.0.5/32 -p tcp -m tcp --dport 8443 -m conntrack --ctstate DNAT -m comment --comment "mon-dnat:vless:in@10.0.0.5" -j ACCEPT\n'
        fwd += '[20:2000] -A MON_DNAT_FWD -s 10.0.0.5/32 -p tcp -m tcp --sport 8443 -m conntrack --ctstate DNAT -m comment --comment "mon-dnat:vless:out@10.0.0.5" -j ACCEPT\n'
        counters, missing = summarize([multi], nat, fwd, MANGLE_DUMP)
        self.assertEqual(counters[0]["conns"], 10)
        self.assertEqual(counters[0]["bytes_in"], 21000)
        self.assertEqual([t["ip"] for t in counters[0]["targets"]], ["10.0.0.2", "10.0.0.5"])
        self.assertTrue(all(t["present"] for t in counters[0]["targets"]))
        # обе цели на месте, но HMARK-строки нет — без неё DNAT по метке не сработает
        self.assertEqual(missing, ["vless"])
        with_hash = nat + '[13:780] -A MON_DNAT -p tcp -m tcp --dport 443 -m comment --comment "mon-dnat:vless#hash" -j HMARK --hmark-tuple src --hmark-mod 2 --hmark-offset 0x4d440000 --hmark-rnd 0x6d6f6e64\n'
        self.assertEqual(summarize([multi], with_hash, fwd, MANGLE_DUMP)[1], [])

    def test_missing_jump_reported(self):
        counters, missing = summarize([rule()], NAT_DUMP.replace("[10:600] -A PREROUTING -j MON_DNAT\n", ""), FILTER_DUMP, MANGLE_DUMP)
        self.assertIn("jump:nat/PREROUTING", missing)
        self.assertTrue(counters[0]["present"])
        # без дампа mangle джамп маскировки считается потерянным
        self.assertIn("jump:mangle/FORWARD", summarize([rule()], NAT_DUMP, FILTER_DUMP)[1])

    def test_mask_ttl_requires_mangle_rules(self):
        masked = rule(mask_ttl=True)
        counters, missing = summarize([masked], NAT_DUMP, FILTER_DUMP, MANGLE_DUMP)
        self.assertFalse(counters[0]["present"])
        self.assertEqual(missing, ["vless"])
        with_ttl = MANGLE_DUMP + (
            '[1:60] -A MON_DNAT_MANGLE -d 10.0.0.2/32 -p tcp -m tcp --dport 8443 -m conntrack --ctstate DNAT -m comment --comment "mon-dnat:vless:ttl-in@10.0.0.2" -j TTL --ttl-set 64\n'
            '[1:60] -A MON_DNAT_MANGLE -s 10.0.0.2/32 -p tcp -m tcp --sport 8443 -m conntrack --ctstate DNAT -m comment --comment "mon-dnat:vless:ttl-out@10.0.0.2" -j TTL --ttl-set 64\n'
        )
        self.assertEqual(summarize([masked], NAT_DUMP, FILTER_DUMP, with_ttl)[1], [])


# Тот же вектор и хэш лежат в panel/backend/tests/test_dnat_profiles.py:
# формула на двух сторонах обязана совпадать, иначе панель увидит вечный drift
GOLDEN_RULES = [
    {"name": "hop", "protocol": "udp", "listen_port": 20000, "listen_port_end": 30000, "target_ip": "10.0.0.3",
     "target_port": 0, "masquerade": True, "enabled": True, "comment": "hysteria"},
    {"name": "vless", "protocol": "tcp", "listen_port": 443, "listen_port_end": 443, "target_ip": "10.0.0.2",
     "target_port": 8443, "masquerade": False, "enabled": False, "comment": ""},
]
GOLDEN_HASH = "281199e72b412545ccd7fc9967b02812e5123c266df98e1f97e25d53de7f0327"


class HashTest(unittest.TestCase):
    def test_golden_vector_matches_panel(self):
        self.assertEqual(compute_rules_hash(GOLDEN_RULES), GOLDEN_HASH)

    def test_comment_and_order_ignored(self):
        a = [rule(comment="x").model_dump(), rule(name="b", listen_port=444).model_dump()]
        b = [rule(name="b", listen_port=444, comment="y").model_dump(), rule().model_dump()]
        self.assertEqual(compute_rules_hash(a), compute_rules_hash(b))

    def test_range_end_equal_start_same_hash(self):
        self.assertEqual(
            compute_rules_hash([{"name": "a", "listen_port": 443, "listen_port_end": 443, "target_ip": "1.1.1.1"}]),
            compute_rules_hash([{"name": "a", "listen_port": 443, "target_ip": "1.1.1.1"}]),
        )

    def test_distribution_and_targets_change_hash(self):
        base = rule(target_ip="10.0.0.2,10.0.0.3", distribution="random").model_dump()
        other = rule(target_ip="10.0.0.2,10.0.0.3", distribution="round_robin").model_dump()
        self.assertNotEqual(compute_rules_hash([base]), compute_rules_hash([other]))
        self.assertNotEqual(compute_rules_hash([base]), compute_rules_hash([rule(target_ip="10.0.0.2", distribution="random").model_dump()]))

    def test_mask_ttl_changes_hash(self):
        self.assertNotEqual(compute_rules_hash([rule().model_dump()]), compute_rules_hash([rule(mask_ttl=True).model_dump()]))

    def test_enabled_changes_hash(self):
        self.assertNotEqual(
            compute_rules_hash([rule().model_dump()]),
            compute_rules_hash([rule(enabled=False).model_dump()]),
        )


class StateFileTest(unittest.TestCase):
    def test_roundtrip_and_ensure_without_rules(self):
        with tempfile.TemporaryDirectory() as tmp:
            manager = DnatManager(state_path=Path(tmp) / "dnat_rules.json")
            self.assertEqual(manager.load_state(), ([], None))
            manager._save_state([rule()])
            rules, applied_at = manager.load_state()
            self.assertEqual(rules[0].name, "vless")
            self.assertIsNotNone(applied_at)
            self.assertEqual(json.loads((Path(tmp) / "dnat_rules.json").read_text())["rules"][0]["target_port"], 8443)

    def test_ensure_applied_noop_without_state(self):
        with tempfile.TemporaryDirectory() as tmp:
            manager = DnatManager(state_path=Path(tmp) / "dnat_rules.json")
            self.assertIsNone(asyncio.run(manager.ensure_async()))

    def test_state_without_rules_does_not_dump_tables(self):
        with tempfile.TemporaryDirectory() as tmp:
            manager = DnatManager(state_path=Path(tmp) / "dnat_rules.json")
            calls: list[list[str]] = []
            manager._run = lambda command, stdin=None: (calls.append(command) or (0, "", ""))  # type: ignore[method-assign]
            state = manager.state()
            self.assertTrue(state["available"])
            self.assertTrue(state["healthy"])
            self.assertEqual(state["rules"], [])
            self.assertFalse(any(command[0] == "iptables-save" for command in calls))


if __name__ == "__main__":
    unittest.main()
