"""Tests for the per-port iptables counter sampler.

Runnable with plain stdlib:  python -m unittest discover -s tests -p "test_*.py"
(from the node/ directory — no psutil and no iptables on the machine).

The bug these exist for: the previous collector matched counters by looking for
the substring `dpt:{port}` in `iptables -L` output, so port 80 also matched every
`dpt:8080` line and quietly absorbed that port's traffic. The replacement reads
`iptables-save -c` and takes the port as a rule token, which is what the first
test pins down.
"""

import asyncio
import json
import os
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.services import port_traffic_sampler  # noqa: E402
from app.services.port_traffic_sampler import PortTrafficSampler, parse_port_counters  # noqa: E402


# Counters are [packets:bytes]. Both accounting chains carry a tcp and a udp rule
# per tracked port, so the expected value per direction is the sum of the two.
# The dump deliberately also holds decoys: an ACCEPT rule in INPUT that mentions
# --dport 80, and a port-range rule that has no single port to bill.
IPTABLES_SAVE_DUMP = """\
# Generated by iptables-save v1.8.7 on Sat Aug  8 12:00:00 2026
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
:TRAFFIC_ACCOUNTING_IN - [0:0]
:TRAFFIC_ACCOUNTING_OUT - [0:0]
[9876:1234567] -A INPUT -j TRAFFIC_ACCOUNTING_IN
[4321:7654321] -A OUTPUT -j TRAFFIC_ACCOUNTING_OUT
[500:99999999] -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
[10:1000] -A TRAFFIC_ACCOUNTING_IN -p tcp -m tcp --dport 80
[20:2000] -A TRAFFIC_ACCOUNTING_IN -p udp -m udp --dport 80
[30:3000] -A TRAFFIC_ACCOUNTING_IN -p tcp -m tcp --dport 8080
[40:4000] -A TRAFFIC_ACCOUNTING_IN -p udp -m udp --dport 8080
[7:700000] -A TRAFFIC_ACCOUNTING_IN -p tcp -m tcp --dport 8000:8100
[50:5000] -A TRAFFIC_ACCOUNTING_OUT -p tcp -m tcp --sport 80
[60:6000] -A TRAFFIC_ACCOUNTING_OUT -p udp -m udp --sport 80
[70:7000] -A TRAFFIC_ACCOUNTING_OUT -p tcp -m tcp --sport 8080
[80:8000] -A TRAFFIC_ACCOUNTING_OUT -p udp -m udp --sport 8080
COMMIT
"""

PORT_80 = {"rx_bytes": 3000, "tx_bytes": 11000}
PORT_8080 = {"rx_bytes": 7000, "tx_bytes": 15000}


class FakeIptables:
    """Stands in for PortTrafficSampler._exec, the single place the class forks.

    Scripted rather than recorded: a test says "iptables is missing" or "here is
    the dump", and every attempted command is kept so the no-I/O and
    reject-before-touching-the-firewall properties can be asserted.
    """

    def __init__(self, dump: str = "", reachable: bool = True):
        self.dump = dump
        self.reachable = reachable
        self.calls: list[list[str]] = []

    async def __call__(self, command: list[str]) -> tuple[int, str]:
        self.calls.append(list(command))
        if not self.reachable:
            return port_traffic_sampler.EXEC_FAILED, ""
        if command[0] == "iptables-save":
            return 0, self.dump
        return 0, ""


class SamplerTestCase(unittest.TestCase):
    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.config_path = Path(tmp.name) / "traffic_config.json"

    def make_sampler(self, tracked=None, dump="", reachable=True):
        """A sampler wired to a temp config and a fake firewall.

        The real config path lives under /var/lib/monitoring; leaving it alone
        would make add/remove write outside the test.
        """
        if tracked is not None:
            self.config_path.write_text(json.dumps({"tracked_ports": list(tracked)}))

        sampler = PortTrafficSampler()
        sampler._config_path = self.config_path
        fake = FakeIptables(dump=dump, reachable=reachable)
        sampler._exec = fake
        return sampler, fake


class ParsePortCountersTests(unittest.TestCase):
    def test_port_80_does_not_swallow_8080(self):
        # The regression: substring matching on `dpt:80` also hit `dpt:8080`,
        # so port 80 reported its own traffic plus all of 8080's.
        counters = parse_port_counters(IPTABLES_SAVE_DUMP)
        self.assertEqual(counters[80], PORT_80)
        self.assertEqual(counters[8080], PORT_8080)

    def test_rules_outside_the_accounting_chains_are_ignored(self):
        # A plain ACCEPT rule in INPUT matches --dport 80 just as well; billing
        # it would inflate the port by the whole machine's traffic.
        dump = "[500:99999999] -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT\n"
        self.assertEqual(parse_port_counters(dump), {})

    def test_direction_follows_the_chain(self):
        # IN counts --dport, OUT counts --sport. Swapping them would report the
        # mirror of every port's real traffic.
        dump = (
            "[1:111] -A TRAFFIC_ACCOUNTING_IN -p tcp -m tcp --dport 443\n"
            "[2:222] -A TRAFFIC_ACCOUNTING_OUT -p tcp -m tcp --sport 443\n"
        )
        self.assertEqual(parse_port_counters(dump), {443: {"rx_bytes": 111, "tx_bytes": 222}})

    def test_port_range_rule_is_skipped(self):
        # `--dport 8000:8100` has no single port to attribute the bytes to.
        counters = parse_port_counters(IPTABLES_SAVE_DUMP)
        self.assertNotIn(8000, counters)
        self.assertEqual(sorted(counters), [80, 8080])

    def test_dump_without_counters_yields_nothing(self):
        # `iptables-save` without -c prints no [packets:bytes] prefix at all.
        dump = "*filter\n-A TRAFFIC_ACCOUNTING_IN -p tcp -m tcp --dport 80\nCOMMIT\n"
        self.assertEqual(parse_port_counters(dump), {})


class SnapshotTests(SamplerTestCase):
    def test_tracked_ports_are_reported_after_a_sample(self):
        sampler, _ = self.make_sampler(tracked=[80, 8080], dump=IPTABLES_SAVE_DUMP)

        async def scenario():
            await sampler.init()
            await sampler._sample()
            return sampler.snapshot()

        ports, available, sampled_at = asyncio.run(scenario())
        self.assertTrue(available)
        self.assertIsNotNone(sampled_at)
        self.assertEqual(
            ports,
            [{"port": 80, **PORT_80}, {"port": 8080, **PORT_8080}],
        )

    def test_idle_port_reports_zero(self):
        # `iptables-save -c` prints every rule, including ones that never
        # matched, as [0:0] — so an idle port is present in the dump and must be
        # reported as a real zero.
        idle_dump = IPTABLES_SAVE_DUMP.replace(
            "COMMIT\n",
            "[0:0] -A TRAFFIC_ACCOUNTING_IN -p tcp -m tcp --dport 9999\n"
            "[0:0] -A TRAFFIC_ACCOUNTING_OUT -p tcp -m tcp --sport 9999\n"
            "COMMIT\n",
        )
        sampler, _ = self.make_sampler(tracked=[80, 9999], dump=idle_dump)

        async def scenario():
            await sampler.init()
            complete = await sampler._sample()
            return sampler.snapshot(), complete

        (ports, _, _), complete = asyncio.run(scenario())
        self.assertTrue(complete)
        self.assertEqual(ports[1], {"port": 9999, "rx_bytes": 0, "tx_bytes": 0})

    def test_port_without_accounting_rules_is_omitted_not_zeroed(self):
        # Правила учёта сносит `ufw --force reset` при синке firewall-профиля.
        # Ноль в этот момент неотличим от честной тишины: панель приняла бы шаг
        # счётчика назад за сброс и молча потеряла бы накопленную дельту.
        sampler, _ = self.make_sampler(tracked=[80, 9999], dump=IPTABLES_SAVE_DUMP)

        async def scenario():
            await sampler.init()
            complete = await sampler._sample()
            return sampler.snapshot(), complete

        (ports, available, _), complete = asyncio.run(scenario())
        self.assertFalse(complete)
        self.assertTrue(available)
        self.assertEqual([p["port"] for p in ports], [80])

    def test_snapshot_never_shells_out(self):
        """/api/metrics calls snapshot() on every poll.

        A dump taken there would block on the xtables lock and eat the 10s
        request budget — a slow node is indistinguishable from a dead one to the
        panel. So the call must be pure memory.
        """
        sampler, _ = self.make_sampler(tracked=[80, 8080], dump=IPTABLES_SAVE_DUMP)

        async def prime():
            await sampler.init()
            await sampler._sample()

        asyncio.run(prime())

        def explode(command):
            raise AssertionError(f"snapshot() shelled out: {command}")

        sampler._exec = explode

        ports, available, sampled_at = sampler.snapshot()
        self.assertEqual(ports, [{"port": 80, **PORT_80}, {"port": 8080, **PORT_8080}])
        self.assertTrue(available)
        self.assertIsNotNone(sampled_at)

    def test_snapshot_hands_out_a_copy(self):
        sampler, _ = self.make_sampler(tracked=[80], dump=IPTABLES_SAVE_DUMP)

        async def scenario():
            await sampler.init()
            await sampler._sample()

        asyncio.run(scenario())

        ports, _, _ = sampler.snapshot()
        ports[0]["rx_bytes"] = -1
        ports.clear()

        again, _, _ = sampler.snapshot()
        self.assertEqual(again, [{"port": 80, **PORT_80}])


class MissingIptablesTests(SamplerTestCase):
    def test_snapshot_is_empty_and_flagged_unavailable(self):
        # Containers without NET_ADMIN reach this path on every boot; it has to
        # degrade to "no port data", not to an exception in metrics collection.
        sampler, fake = self.make_sampler(tracked=[80], reachable=False)

        asyncio.run(sampler.init())

        ports, available, sampled_at = sampler.snapshot()
        self.assertEqual(ports, [])
        self.assertFalse(available)
        self.assertIsNone(sampled_at)

    def test_chains_are_not_touched_when_iptables_is_missing(self):
        sampler, fake = self.make_sampler(tracked=[80], reachable=False)

        asyncio.run(sampler.init())

        self.assertEqual(len(fake.calls), 1, fake.calls)
        self.assertNotIn("-N", fake.calls[0])

    def test_adding_a_port_is_refused(self):
        sampler, _ = self.make_sampler(tracked=[], reachable=False)

        async def scenario():
            await sampler.init()
            return await sampler.add_tracked_port(443)

        accepted, message = asyncio.run(scenario())
        self.assertFalse(accepted)
        self.assertIn("iptables", message)
        self.assertEqual(sampler.tracked_ports(), [])


class PortValidationTests(SamplerTestCase):
    def test_out_of_range_ports_are_rejected(self):
        sampler, fake = self.make_sampler(tracked=[], dump=IPTABLES_SAVE_DUMP)

        async def scenario():
            await sampler.init()
            before = len(fake.calls)
            results = {port: await sampler.add_tracked_port(port) for port in (0, -1, 65536, 999999)}
            return results, before, len(fake.calls)

        results, before, after = asyncio.run(scenario())

        for port, (accepted, message) in results.items():
            self.assertFalse(accepted, f"port {port} was accepted")
            self.assertIn("out of range", message)
        self.assertEqual(sampler.tracked_ports(), [])
        # Rejected by the guard clause, before any rule reaches the firewall.
        self.assertEqual(before, after)

    def test_boundary_ports_are_accepted(self):
        # 1 and 65535 are legal ports; an off-by-one in the guard would lose them.
        sampler, _ = self.make_sampler(tracked=[], dump=IPTABLES_SAVE_DUMP)

        async def scenario():
            await sampler.init()
            return [await sampler.add_tracked_port(port) for port in (1, 65535)]

        results = asyncio.run(scenario())
        self.assertTrue(all(accepted for accepted, _ in results), results)
        self.assertEqual(sampler.tracked_ports(), [1, 65535])

    def test_garbage_in_the_config_file_is_filtered_on_load(self):
        # traffic_config.json survives from older node versions and is editable
        # on the host; an out-of-range entry there would turn into an iptables
        # rule that never applies.
        sampler, _ = self.make_sampler(tracked=[80, 0, 70000, -5, 443, 443], dump=IPTABLES_SAVE_DUMP)

        asyncio.run(sampler.init())

        self.assertEqual(sampler.tracked_ports(), [80, 443])


class TrackedPortPersistenceTests(SamplerTestCase):
    def test_add_and_remove_round_trip_through_the_config_file(self):
        sampler, _ = self.make_sampler(tracked=[], dump=IPTABLES_SAVE_DUMP)

        async def scenario():
            await sampler.init()
            await sampler.add_tracked_port(443)
            added = json.loads(self.config_path.read_text())["tracked_ports"]
            await sampler.remove_tracked_port(443)
            return added, json.loads(self.config_path.read_text())["tracked_ports"]

        added, removed = asyncio.run(scenario())
        self.assertEqual(added, [443])
        self.assertEqual(removed, [])
        self.assertEqual(sampler.tracked_ports(), [])

    def test_removing_an_untracked_port_is_reported_not_raised(self):
        sampler, _ = self.make_sampler(tracked=[80], dump=IPTABLES_SAVE_DUMP)

        async def scenario():
            await sampler.init()
            return await sampler.remove_tracked_port(443)

        accepted, message = asyncio.run(scenario())
        self.assertFalse(accepted)
        self.assertIn("not tracked", message)
        self.assertEqual(sampler.tracked_ports(), [80])


if __name__ == "__main__":
    unittest.main()
