"""Развод рабочих нагрузок и сетевых прерываний по разным ядрам.

На хосте без аппаратного multiqueue (`ethtool -l` → `Combined: 1`) весь NAPI-поллинг
сидит на одном ядре — том, к которому гипервизор привязал IRQ карты. Потоки HAProxy
или Xray на этом же ядре отнимают у него время, и потолок скорости задаёт оно одно,
пока остальные ядра простаивают: замеры на боевых нодах давали 65% занятости сетевого
ядра при 54% простоя в среднем по машине.

Номер ядра захардкодить нельзя — привязку выбирает гипервизор, и на разных хостах
это разные ядра (0 и 1 на одном провайдере, 5 и 7 на другом).

Две точки применения: HAProxy получает `nbthread`/`cpu-map` в свой конфиг, контейнеры
Remnawave — `cpuset` через docker update. Механизм один и тот же, отличается только
способ сказать процессу, где ему работать.
"""

import asyncio
import logging
import re
import shlex
from pathlib import Path

logger = logging.getLogger(__name__)

# Маркер в шаблоне панели. В скобках — какие ядра отдать сети: `auto` (нода
# определяет сама), явный список (`0,1`) или `off`. Нет маркера — нода не трогает
# конфиг вообще, поэтому старый профиль продолжает работать как раньше.
MARKER_RE = re.compile(r"^([ \t]*)#[ \t]*cpu-affinity[ \t]*\(([^)]*)\)[ \t]*$", re.MULTILINE)

BLOCK_START = "# --- cpu-affinity: рассчитано нодой, править вручную бесполезно ---"
BLOCK_END = "# --- cpu-affinity end ---"
_BLOCK_RE = re.compile(
    rf"^[ \t]*{re.escape(BLOCK_START)}[ \t]*\n.*?^[ \t]*{re.escape(BLOCK_END)}[ \t]*\n",
    re.MULTILINE | re.DOTALL,
)

# Векторы, не обслуживающие очереди пакетов. Отсеиваются по имени, а не по
# активности: на свежей ноде счётчики нулевые у всех, и virtio-config — привязанный
# к ядру, но не несущий трафика — попал бы в сетевые ядра.
#
# Только чёрный список, без встречной проверки на «rx/tx/input/output» в имени:
# такие суффиксы есть у virtio и многоочередных карт, но встроенные Intel PCH
# (e1000e) называют единственный вектор просто именем интерфейса, и позитивный
# фильтр отбрасывал его вместе со служебными.
_SERVICE_IRQ_RE = re.compile(r"config|admin|async|mbox", re.I)

# Ниже четырёх ядер отдавать два под сеть нечего: приложению останется одно-два.
MIN_CPUS_FOR_SPLIT = 4

PROC_ROUTE = Path("/proc/net/route")
PROC_INTERRUPTS = Path("/proc/interrupts")
SYS_CLASS_NET = Path("/sys/class/net")
PROC_IRQ = Path("/proc/irq")

# Состояние пишет панель при применении системных оптимизаций. Лежит рядом с
# tuning-facts, потому что переживать должно и перезапуск агента, и перезагрузку.
# Каталог смонтирован в контейнер только на чтение — запись идёт через host executor.
STATE_FILE = Path("/opt/monitoring/configs/cpu-affinity.env")
STATE_KEY = "CPU_AFFINITY_ENABLED"
CONTAINERS_KEY = "CPU_AFFINITY_CONTAINERS"

DEFAULT_CONTAINERS = ("remnanode", "remnawave-nginx")

# Контейнеры пересоздаются мимо ноды (docker compose up -d, обновление Remnawave)
# и теряют cpuset, поэтому привязка не выставляется один раз, а подтверждается
# периодически. Проверка — два docker inspect, стоит дёшево.
CONTAINER_RECHECK_INTERVAL_SEC = 300
DOCKER_TIMEOUT_SEC = 15


def _read(path: Path) -> str:
    try:
        return path.read_text()
    except OSError:
        return ""


def _state_value(key: str) -> str:
    for line in _read(STATE_FILE).splitlines():
        name, sep, value = line.partition("=")
        if sep and name.strip() == key:
            return value.strip().strip("\"'")
    return ""


def is_enabled() -> bool:
    """Выключено, пока оператор не включил явно.

    Привязка забирает у приложения ядро целиком, а выигрыш зависит от того, во что
    упирается конкретная нода, — поэтому включение остаётся сознательным действием,
    а отсутствующий файл состояния трактуется как «выключено».
    """
    return _state_value(STATE_KEY).lower() in ("1", "true", "yes", "on")


def container_names() -> list[str]:
    raw = _state_value(CONTAINERS_KEY)
    if not raw:
        return list(DEFAULT_CONTAINERS)
    return [name.strip() for name in raw.split(",") if name.strip()]


def render_state(enabled: bool, containers: list[str] | None = None) -> str:
    names = ",".join(containers or DEFAULT_CONTAINERS)
    return (
        "# Generated by the panel — do not edit.\n"
        f"{STATE_KEY}={'1' if enabled else '0'}\n"
        f"{CONTAINERS_KEY}={names}\n"
    )


def default_interface() -> str | None:
    """Интерфейс дефолтного маршрута из /proc/net/route (Destination = 00000000)."""
    for line in _read(PROC_ROUTE).splitlines()[1:]:
        parts = line.split()
        if len(parts) >= 2 and parts[1] == "00000000":
            return parts[0]
    return None


def _device_name(iface: str) -> str | None:
    """virtio-IRQ называются `virtio1-input.0` — имени интерфейса в них нет,
    поэтому строки в /proc/interrupts ищутся ещё и по имени PCI-устройства."""
    try:
        return (SYS_CLASS_NET / iface / "device").resolve().name
    except OSError:
        return None


def _parse_irq_line(line: str) -> tuple[str, list[int], str] | None:
    irq, _, rest = line.partition(":")
    irq = irq.strip()
    if not irq.isdigit():
        return None

    counters: list[int] = []
    tokens = rest.split()
    for index, token in enumerate(tokens):
        if not token.isdigit():
            return irq, counters, " ".join(tokens[index:])
        counters.append(int(token))
    return irq, counters, ""


def _affinity_cpu(irq: str) -> int | None:
    """Ядро из effective_affinity_list. Диапазон («0-7») означает, что вектор
    никуда не привязан — такой IRQ не считается сетевым ядром."""
    for name in ("effective_affinity_list", "smp_affinity_list"):
        value = _read(PROC_IRQ / irq / name).strip()
        if value.isdigit():
            return int(value)
    return None


def detect_network_cpus(iface: str | None = None) -> set[int]:
    """Ядра, обслуживающие прерывания сетевой карты.

    Есть трафик — ядро берётся по максимуму счётчика (отражает факт, переживает
    любые настройки affinity). Счётчики пустые (нода только поднялась) — по
    effective_affinity_list, который корректен уже сразу после загрузки.
    """
    iface = iface or default_interface()
    if not iface:
        return set()

    device = _device_name(iface)
    cpus: set[int] = set()

    for line in _read(PROC_INTERRUPTS).splitlines():
        if iface not in line and (not device or device not in line):
            continue

        parsed = _parse_irq_line(line)
        if not parsed:
            continue
        irq, counters, name = parsed

        if _SERVICE_IRQ_RE.search(name):
            continue

        if counters and sum(counters) > 0:
            cpus.add(max(range(len(counters)), key=counters.__getitem__))
            continue

        cpu = _affinity_cpu(irq)
        if cpu is not None:
            cpus.add(cpu)

    return cpus


def _parse_cpu_list(value: str) -> set[int] | None:
    """Разбирает `0,1` и `0-2` из ручного переопределения в маркере."""
    cpus: set[int] = set()
    for chunk in value.split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        if "-" in chunk:
            start, _, end = chunk.partition("-")
            if not (start.strip().isdigit() and end.strip().isdigit()):
                return None
            cpus.update(range(int(start), int(end) + 1))
        elif chunk.isdigit():
            cpus.add(int(chunk))
        else:
            return None
    return cpus


def _irqbalance_running() -> bool:
    """Живой irqbalance перетасовывает векторы между ядрами, и любая статичная
    привязка со временем разъезжается — тогда лучше не трогать конфиг вовсе."""
    for proc in Path("/proc").iterdir():
        if not proc.name.isdigit():
            continue
        if _read(proc / "comm").strip() == "irqbalance":
            return True
    return False


def resolve_app_cpus(value: str, cpu_count: int) -> list[int] | None:
    """Ядра под приложение: все, кроме сетевых. None — применять не нужно."""
    value = value.strip().lower()
    if value in ("off", "no", "false", ""):
        return None

    if value == "auto":
        if _irqbalance_running():
            logger.info("cpu-affinity skipped: irqbalance is running")
            return None
        network_cpus = detect_network_cpus()
    else:
        network_cpus = _parse_cpu_list(value)
        if network_cpus is None:
            logger.warning("cpu-affinity: cannot parse %r, skipping", value)
            return None

    if not network_cpus:
        logger.info("cpu-affinity skipped: network CPUs not detected")
        return None

    if cpu_count < MIN_CPUS_FOR_SPLIT:
        logger.info("cpu-affinity skipped: only %d CPUs", cpu_count)
        return None

    app_cpus = [cpu for cpu in range(cpu_count) if cpu not in network_cpus]

    # Меньше половины машины под приложение — значит сетевых ядер неправдоподобно
    # много (multiqueue разложен на все ядра, кривой парсинг). Ничего не делаем.
    if len(app_cpus) * 2 < cpu_count:
        logger.info(
            "cpu-affinity skipped: %d/%d CPUs left for the application",
            len(app_cpus), cpu_count,
        )
        return None

    return app_cpus


def to_cpuset(cpus: list[int]) -> str:
    """Список ядер в форму, которую понимает docker --cpuset-cpus."""
    return ",".join(str(cpu) for cpu in cpus)


def render_block(haproxy_cpus: list[int], indent: str) -> str:
    lines = [
        f"{indent}{BLOCK_START}",
        f"{indent}nbthread {len(haproxy_cpus)}",
    ]
    lines += [
        f"{indent}cpu-map 1/{thread} {cpu}"
        for thread, cpu in enumerate(haproxy_cpus, start=1)
    ]
    lines.append(f"{indent}{BLOCK_END}")
    return "\n".join(lines) + "\n"


def apply(content: str, cpu_count: int) -> str:
    """Вписывает nbthread/cpu-map в секцию global.

    Выключателем служит настройка в панели, а не наличие маркера в конфиге:
    конфиги на давно работающих нодах созданы прежним шаблоном, и требование
    маркера означало бы, что включённый тумблер на них молча не делает ничего.
    Поэтому без маркера значения вписываются в начало `global` — так же, как
    это делает `_ensure_global_maxconn`. Маркер остаётся способом переопределить
    поведение на отдельной ноде: задать сетевые ядра списком или указать `off`.

    Ранее сгенерированный блок всегда вырезается и считается заново — иначе смена
    тарифа (другое число ядер) или переезд IRQ оставили бы устаревшую привязку.
    Выключённая настройка тоже проходит через вырезание: так конфиг очищается от
    прошлой привязки сразу при следующем применении, а не остаётся с ней навсегда.
    """
    content = _BLOCK_RE.sub("", content)

    if not is_enabled():
        return content

    match = MARKER_RE.search(content)
    value = match.group(2) if match else "auto"

    app_cpus = resolve_app_cpus(value, cpu_count)
    if not app_cpus:
        return content

    if match:
        indent, insert_at = match.group(1), match.end() + 1
    else:
        global_match = re.search(r"^global[ \t]*\n", content, re.MULTILINE)
        if not global_match:
            logger.warning("cpu-affinity: no global section in the config, skipping")
            return content
        indent, insert_at = "    ", global_match.end()

    logger.info("cpu-affinity: HAProxy pinned to CPUs %s", app_cpus)
    return content[:insert_at] + render_block(app_cpus, indent) + content[insert_at:]


async def _container_cpuset(executor, name: str) -> str | None:
    """Текущий cpuset контейнера. None — контейнера на ноде нет."""
    result = await executor.execute(
        f"docker inspect -f '{{{{.HostConfig.CpusetCpus}}}}' {shlex.quote(name)}",
        timeout=DOCKER_TIMEOUT_SEC,
    )
    if not result.success:
        return None
    return result.stdout.strip()


async def sync_containers(executor, cpu_count: int) -> dict[str, str]:
    """Приводит cpuset контейнеров к расчётному набору ядер.

    Возвращает {контейнер: что сделано} только для тех, где что-то поменялось —
    вызывается по таймеру, и логировать «всё как было» на каждом круге незачем.
    """
    if not is_enabled():
        return {}

    app_cpus = resolve_app_cpus("auto", cpu_count)
    if not app_cpus:
        return {}

    wanted = to_cpuset(app_cpus)
    changed: dict[str, str] = {}

    for name in container_names():
        current = await _container_cpuset(executor, name)
        if current is None or current == wanted:
            continue

        result = await executor.execute(
            f"docker update --cpuset-cpus {shlex.quote(wanted)} {shlex.quote(name)}",
            timeout=DOCKER_TIMEOUT_SEC,
        )
        if result.success:
            changed[name] = wanted
            logger.info("cpu-affinity: %s pinned to CPUs %s", name, wanted)
        else:
            logger.warning("cpu-affinity: %s update failed: %s", name, result.stderr.strip())

    return changed


async def reset_containers(executor) -> dict[str, str]:
    """Снимает cpuset — иначе выключение настройки оставило бы контейнеры
    привязанными до ближайшего пересоздания."""
    changed: dict[str, str] = {}
    for name in container_names():
        current = await _container_cpuset(executor, name)
        if not current:
            continue
        result = await executor.execute(
            f"docker update --cpuset-cpus '' {shlex.quote(name)}",
            timeout=DOCKER_TIMEOUT_SEC,
        )
        if result.success:
            changed[name] = ""
            logger.info("cpu-affinity: %s unpinned", name)
        else:
            logger.warning("cpu-affinity: %s reset failed: %s", name, result.stderr.strip())
    return changed


class ContainerAffinitySync:
    """Периодически подтверждает cpuset контейнеров.

    Разово выставить нельзя: `docker compose up -d` и обновление Remnawave
    пересоздают контейнер с настройками из compose-файла, теряя привязку.
    """

    def __init__(self, executor, cpu_count: int, interval: int = CONTAINER_RECHECK_INTERVAL_SEC):
        self._executor = executor
        self._cpu_count = cpu_count
        self._interval = interval
        self._task: asyncio.Task | None = None

    async def start(self) -> None:
        if self._task and not self._task.done():
            return
        self._task = asyncio.create_task(self._loop())

    async def stop(self) -> None:
        if not self._task:
            return
        self._task.cancel()
        try:
            await self._task
        except asyncio.CancelledError:
            pass
        self._task = None

    async def _loop(self) -> None:
        while True:
            try:
                await sync_containers(self._executor, self._cpu_count)
            except asyncio.CancelledError:
                raise
            except Exception as e:
                logger.error("cpu-affinity container sync failed: %s", e, exc_info=True)
            await asyncio.sleep(self._interval)
