export const FAQ_SCREENS = {
  PAGE_DASHBOARD: 'PAGE_DASHBOARD',
  PAGE_SERVERS: 'PAGE_SERVERS',
  PAGE_SERVER_DETAILS: 'PAGE_SERVER_DETAILS',
  PAGE_HAPROXY: 'PAGE_HAPROXY',
  PAGE_TRAFFIC: 'PAGE_TRAFFIC',
  PAGE_ALERTS: 'PAGE_ALERTS',
  PAGE_BULK_ACTIONS: 'PAGE_BULK_ACTIONS',
  PAGE_SSH_SECURITY: 'PAGE_SSH_SECURITY',
  PAGE_SYSTEM_OPTIMIZATIONS: 'PAGE_SYSTEM_OPTIMIZATIONS',
  PAGE_HAPROXY_CONFIGS: 'PAGE_HAPROXY_CONFIGS',
  PAGE_REMNAWAVE: 'PAGE_REMNAWAVE',
  PAGE_BILLING: 'PAGE_BILLING',
  PAGE_BLOCKLIST: 'PAGE_BLOCKLIST',
  PAGE_TORRENT_BLOCKER: 'PAGE_TORRENT_BLOCKER',
  PAGE_WILDCARD_SSL: 'PAGE_WILDCARD_SSL',
  PAGE_UPDATES: 'PAGE_UPDATES',
  PAGE_SETTINGS: 'PAGE_SETTINGS',

  ALERTS_TELEGRAM: 'ALERTS_TELEGRAM',
  ALERTS_TRIGGER_OFFLINE: 'ALERTS_TRIGGER_OFFLINE',
  ALERTS_TRIGGER_CPU: 'ALERTS_TRIGGER_CPU',
  ALERTS_TRIGGER_RAM: 'ALERTS_TRIGGER_RAM',
  ALERTS_TRIGGER_NETWORK: 'ALERTS_TRIGGER_NETWORK',
  ALERTS_TRIGGER_LOADAVG: 'ALERTS_TRIGGER_LOADAVG',
  ALERTS_TRIGGER_TCP: 'ALERTS_TRIGGER_TCP',

  HAPROXY_SSL: 'HAPROXY_SSL',
  HAPROXY_FIREWALL: 'HAPROXY_FIREWALL',

  HAPROXY_CONFIGS_BALANCER: 'HAPROXY_CONFIGS_BALANCER',
  HAPROXY_CONFIGS_STICKY: 'HAPROXY_CONFIGS_STICKY',
  HAPROXY_CONFIGS_HEALTHCHECK: 'HAPROXY_CONFIGS_HEALTHCHECK',

  SSH_SECURITY_SSHD: 'SSH_SECURITY_SSHD',
  SSH_SECURITY_FAIL2BAN: 'SSH_SECURITY_FAIL2BAN',
  SSH_SECURITY_KEYS: 'SSH_SECURITY_KEYS',

  SYS_OPT_PROFILE: 'SYS_OPT_PROFILE',
  SYS_OPT_NIC_MODE: 'SYS_OPT_NIC_MODE',

  BULK_ACTIONS_TERMINAL: 'BULK_ACTIONS_TERMINAL',

  TRAFFIC_TCP_STATES: 'TRAFFIC_TCP_STATES',
  TRAFFIC_PORT_TRACKING: 'TRAFFIC_PORT_TRACKING',

  REMNAWAVE_HWID_ANOMALIES: 'REMNAWAVE_HWID_ANOMALIES',

  BILLING_QUOTA: 'BILLING_QUOTA',

  BLOCKLIST_SOURCES: 'BLOCKLIST_SOURCES',

  WILDCARD_SSL_ACME: 'WILDCARD_SSL_ACME',

  SETTINGS_BACKUP: 'SETTINGS_BACKUP',
  SETTINGS_TIME_SYNC: 'SETTINGS_TIME_SYNC',

  DASHBOARD_FOLDERS: 'DASHBOARD_FOLDERS',

  SERVER_DETAILS_TERMINAL: 'SERVER_DETAILS_TERMINAL',
} as const

export type FAQScreen = (typeof FAQ_SCREENS)[keyof typeof FAQ_SCREENS]

export type FAQLang = 'ru' | 'en'
